language: php

php:
- 7.1
- 7.2

install:
- travis_retry composer install --no-interaction --prefer-source

script:
- vendor/bin/phpunit
- vendor/bin/phpcs --standard=psr2 src/ -n

matrix:
  fast_finish: true
